apiVersion: apps/v1
kind: Deployment
metadata:
  name: javamaven
  labels:
    app: javamaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javamaven
  template:
    metadata:
      labels:
        app: javamaven
    spec:
      containers:
      - name: javamaven
        image: sreedocker123/cafewebimage:final
        ports:
        - containerPort: 80
