apiVersion: v1
kind: Service
metadata:
  name: javamaven
  labels:
    app: javamaven
spec:
  type: NodePort
  selector:
    app: javamaven
  ports:
    - port: 8081        # Service port
      targetPort: 8080  # Container port (Tomcat)
      #nodePort: 30080   # Optional: specify, else Kubernetes assigns one
      protocol: TCP
